spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/entrepnet
    username: postgres
    password: mdsoln
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  error:
    include-message: always
logging:
  level:
    org.springframework.security: DEBUG
clickSend-username: mnyamaki698@gmail.com
clickSend-apiKey: 1E721529-C901-DA68-020E-F657C42D7388