version: '3.8'

services:
  # PostgreSQL database service
  postgresql:
    build:
      context: .
      dockerfile: Dockerfile.postgresql
    container_name: postgres_db
    # Map port 5432 of the container to port 5432 of the host machine
    ports:
      - "5433:5432"
    # Create a volume named 'entrepnet' to store persistent database data
    volumes:
      - entrepnet:/var/lib/postgresql/data

  # Custom PostgreSQL Express service
  postgresql_express:
    build:
      context: .
      dockerfile: Dockerfile.postgres-express
    container_name: postgres_express
    # Restart the container automatically if it crashes
    restart: always
    ports:
      - "8081:8081"
    environment:
      PE_CONFIG_POSTGRESQL_HOST: 'postgresql'
      PE_CONFIG_POSTGRESQL_PORT: 5432
      # PostgreSQL Express configuration
      PE_CONFIG_POSTGRESQL_USERNAME: 'postgres'
      PE_CONFIG_POSTGRESQL_PASSWORD: 'mdsoln'
      PE_CONFIG_POSTGRESQL_DATABASE: 'entrepnet'

volumes:
  entrepnet: {}
